name: release ci
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    override_tag:
      description: 'Override auto generate tag.'
      required: false
      type: string

jobs:
  build:
    runs-on: macos-latest
    env:
      SQUIRREL_BUNDLED_RECIPES: 'lotem/rime-octagram-data lotem/rime-octagram-data@hant'
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Build Squirrel
        run: ./action-build.sh archive

      # - name: Build changelog
      #   id: release_log
      #   run: |
      #     echo 'changelog<<EOF' >> $GITHUB_OUTPUT
      #     ./action-changelog.sh || echo "YEP." >> $GITHUB_OUTPUT
      #     echo 'EOF' >> $GITHUB_OUTPUT

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: package/*.zip
          name: squirrel

      - name: Create Release Info
        id: release_info
        run:  |
          echo "TAG_NAME=$(date +'c%Y%m%d')" >> $GITHUB_OUTPUT
          echo "RELEASE_NAME=$(date +'%Y.%m.build-%d.%H%M')" >> $GITHUB_OUTPUT

      - name: Create release
        uses: ncipollo/release-action@v1
        id: release
        with:
          artifacts: "package/*.zip"
          tag: ${{ steps.release_info.outputs.TAG_NAME }}
          name: ${{ steps.release_info.outputs.RELEASE_NAME }}
          commit: ${{ github.ref_name }}
          draft: true
